name: Example

on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    
    steps:
     - name: checkoutcode 
       uses: actions/checkout@v2
     - name: Test
       run: |
        cat policy.rego 
        pwd
